# Generated by Django 3.2 on 2021-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(default='', max_length=10, unique=True, verbose_name='负责人（导师）')),
                ('research_direction', models.CharField(default='无', max_length=100, verbose_name='研究方向')),
                ('num_dorctors', models.PositiveIntegerField(default=0, verbose_name='博士生数量')),
                ('num_masters', models.PositiveIntegerField(default=0, verbose_name='硕士生数量')),
                ('total_num', models.PositiveIntegerField(default=0, verbose_name='总人数')),
                ('total_found', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总研究经费（万）')),
            ],
            options={
                'db_table': '实验室情况',
            },
        ),
        migrations.CreateModel(
            name='meeting_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(default='', max_length=10, verbose_name='楼号')),
                ('room_number', models.CharField(default='', max_length=10, verbose_name='会议室')),
                ('occupied', models.BooleanField(default=False, verbose_name='是否被占用')),
                ('time_range_occupied', models.CharField(default='', max_length=100, verbose_name='占用的时间段')),
                ('lab_occupying', models.CharField(default='无', max_length=12, verbose_name='占用人')),
                ('phone_number', models.CharField(default='无', max_length=45, verbose_name='联系方式')),
                ('function', models.CharField(default='无', max_length=45, verbose_name='用途')),
            ],
            options={
                'db_table': 'meeting_room',
            },
        ),
        migrations.CreateModel(
            name='research_direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_dire', models.CharField(default='', max_length=100, unique=True, verbose_name='研究方向')),
                ('school_included', models.CharField(default='', max_length=10, verbose_name='所涉院系')),
                ('labs_included', models.PositiveIntegerField(default=0, verbose_name='所涉实验组数量')),
                ('num_researcher', models.PositiveIntegerField(default=0, verbose_name='所涉研究人员数量')),
                ('research_founds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总科研经费（万）')),
            ],
            options={
                'db_table': '研究方向',
            },
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='', max_length=100, unique=True, verbose_name='学院名称')),
                ('leader', models.CharField(default='', max_length=100, unique=True, verbose_name='院长')),
                ('num_faculty', models.PositiveIntegerField(default=0, verbose_name='教职工数量')),
                ('num_student', models.PositiveIntegerField(default=0, verbose_name='学会数量')),
            ],
            options={
                'db_table': '学院',
            },
        ),
        migrations.CreateModel(
            name='xueyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True, verbose_name='姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.CharField(default='', max_length=10, verbose_name='性别')),
                ('graduate_institution', models.CharField(default='', max_length=10, verbose_name='目前最高学位毕业院校')),
                ('positions', models.CharField(default='无', max_length=10, verbose_name='职位')),
                ('title', models.CharField(default='无', max_length=11, verbose_name='职称')),
                ('degree', models.CharField(default='无', max_length=10, verbose_name='正在研修的学位')),
            ],
            options={
                'db_table': '薛羽组',
            },
        ),
    ]
