# Generated by Django 3.2 on 2021-06-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='labs',
            table='labs',
        ),
        migrations.AlterModelTable(
            name='research_direction',
            table='research_direction',
        ),
        migrations.AlterModelTable(
            name='school',
            table='schol',
        ),
        migrations.AlterModelTable(
            name='xueyu',
            table='xueyu',
        ),
    ]
