# Generated by Django 3.2 on 2021-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0004_auto_20210610_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_direction',
            name='num_researcher',
            field=models.PositiveIntegerField(default=0, verbose_name='研究人员数量'),
        ),
    ]
