# Generated by Django 3.2 on 2021-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0005_alter_research_direction_num_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_direction',
            name='school_included',
            field=models.CharField(default='', max_length=1000, verbose_name='所涉院系'),
        ),
    ]
