# Generated by Django 3.2 on 2021-06-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0006_alter_research_direction_school_included'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labs',
            old_name='num_dorctors',
            new_name='num_doctors',
        ),
    ]
