# Generated by Django 3.2 on 2021-06-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0007_rename_num_dorctors_labs_num_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xueyu',
            name='graduate_institution',
            field=models.CharField(default='', max_length=10, verbose_name='最高学位毕业院校'),
        ),
    ]
