# Generated by Django 3.2 on 2021-06-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0008_alter_xueyu_graduate_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=40, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('gender', models.CharField(default='', max_length=50, verbose_name='性别')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户数据',
                'verbose_name_plural': '用户数据',
                'db_table': 'user',
            },
        ),
        migrations.AlterModelOptions(
            name='meeting_room',
            options={'verbose_name': '会议室', 'verbose_name_plural': '会议室'},
        ),
        migrations.AlterModelOptions(
            name='xueyu',
            options={'verbose_name': '薛羽组', 'verbose_name_plural': '薛羽组'},
        ),
    ]
