# Generated by Django 3.2 on 2021-06-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0009_auto_20210614_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research_direction',
            options={'verbose_name': '研究方向', 'verbose_name_plural': '研究方向'},
        ),
    ]
