# Generated by Django 3.2 on 2021-06-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0010_alter_research_direction_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_login',
            table='users',
        ),
    ]
