# Generated by Django 3.2 on 2021-07-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0012_xueyu_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_room',
            name='time_range_occupied',
            field=models.CharField(default='', max_length=100, verbose_name='占用日期'),
        ),
    ]
