# Generated by Django 3.2 on 2021-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0014_auto_20210716_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='identity',
            field=models.CharField(default='', max_length=100, verbose_name='证件号码'),
        ),
    ]
