# Generated by Django 3.2 on 2021-07-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0015_alter_user_login_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_room',
            name='occupied',
        ),
    ]
